### ISSUE TITLE
Prueba con detectron2

### ISSUE THREAD

**Issue by Josemi** [Josemi/TFM-FIS-IA#2]
Enlace: https://github.com/facebookresearch/detectron2

**Comment by Josemi** [comment]
Se está realizando el siguiente [tutorial](https://colab.research.google.com/drive/16jcaJoc6bCFAQ96jDe2HwtXj7BMD_-m5#scrollTo=HUjkwRsOn1O0), pero al ejecutar detectron2 por primera vez sale un mensaje de que se necesitan actualizar los drivers de la tarjeta gráfica. Voy a intentar seguir en local.

**Comment by alvarag** [comment]
Si vemos que es obligatoria la actualización, lo valoraremos. Necesitaré saber qué versión necesita para poder funcionar.

**Comment by Josemi** [comment]
Tras haberse actualizado  los drivers he conseguido completar el notebook de ejemplo, realizando los cambios necesarios (por el cambio de Google Colab a Jupyter Notebook).
El siguiente paso será intentar crear un modelo, para decidir que herramienta usar para la detección de movimiento.
