### ISSUE TITLE
Realizar cambios en la memoria

### ISSUE THREAD

**Issue by Josemi** [Josemi/TFM-FIS-IA#35]

**Comment by alvarag** [comment]
Adjunto las fotos del montaje en un salón.

![IMG_20200528_140625](https://user-images.githubusercontent.com/9881614/83260218-aeafcd00-a1b9-11ea-9d4a-2024797d3754.jpg)
![IMG_20200528_140612](https://user-images.githubusercontent.com/9881614/83260281-ca1ad800-a1b9-11ea-8701-08183fb845b3.jpg)
