### ISSUE TITLE
Pequeñas correcciones en la documentación

### ISSUE THREAD

**Issue by cgosorio** [Josemi/TFM-FIS-IA#75]
He visto algunas cosas que podrían corregirse en la memoria:

Tutor: ⭆ Tutores:

feedback on the **patient´s** evolution
⭆ feedback on the **patient's** evolution
(el comando LaTeX es «'», no «´»)

to have to move to **others** locations to do their **rehablitations**, what
considering their **dependecy** and their old age, it is a big problem.
⭆ to have to move to **other** locations to do their **rehabilitations**, what
  considering their **dependency** and their old age, it is a big problem.

el avance en las tecnologías de telecomunicación **han** permitido el desarrollo de rehabilitaciones online
⭆ el avance en las tecnologías de telecomunicación **ha** permitido el desarrollo de rehabilitaciones online

El **desarrollo** de la aplicación web para el soporte del sistema fue **desarrollado** de manera conjunta
⭆ El desarrollo de la aplicación web para el soporte del sistema fue **llevado a cabo** de manera conjunta
(el «desarrollo fue desarrollado» no suena muy bien)

se podrían haber realizado si se **tuviese** más tiempo o más recursos económicos
⭆ se podrían haber realizado si se **hubiese tenido** más tiempo o más recursos económicos

delimitar el espacio los distintos objetos
⭆ delimitar el espacio **de** los distintos objetos

Este tipo de capa es muy **importantes** **utilizarlas** después de las capas «pesadas»
⭆ Este tipo de capa es muy **importante** **utilizarla** después de las capas «pesadas»

un tipo de dato son los **tensors**, matrices multidimensionales
⭆ un tipo de dato son los **tensores**, matrices multidimensionales

la mejor forma de organizar este **apartado** es en secciones donde se comenta cada **apartado** del desarrollo
⭆ la mejor forma de organizar este apartado es en secciones donde se comenta cada **aspecto** del desarrollo

FIS-HUBU es proyecto que permite realizar vídeo llamadas
⭆ FIS-HUBU es **un** proyecto que permite realizar vídeo llamadas

Las herramientas encontradas **fuera** 
⭆ Las herramientas encontradas **fueron** 

en esta parte se encuentran **unicamente** los ángulos de los codos
⭆ en esta parte se encuentran **únicamente** los ángulos de los codos

codos muy parecidos, aunque **su posición sean** casi contrarias
⭆ codos muy parecidos, aunque **sean posiciones** casi contrarias

La existencia de estas situaciones se **tuvieron** que tener en cuenta en el cálculo
⭆ La existencia de estas situaciones se **tuvo** que tener en cuenta en el cálculo
(la «existencia» es singular)
o alternativamente
⭆ **Estas situaciones** se tuvieron que tener en cuenta en el cálculo

Los resultados obtenidos de la ejecución del flujo con todos sus componentes se **puede** ver en la tabla
⭆ Los resultados obtenidos de la ejecución del flujo con todos sus componentes se **pueden** ver en la tabla
(dado que se está hablando de los resultados, que es plural)

La aparición de las rehabilitaciones online **están** permitiendo la automatización de estos sistemas
⭆ La aparición de las rehabilitaciones online **está** permitiendo la automatización de estos sistemas
(dado que estás hablando de «la aparición» que es singular)

En este **paper** de la Universidad de Valladolid se puede observar
⭆ En este **artículo** de la Universidad de Valladolid se puede observar
(no es necesario el anglicismo)

En el **paper** los creadores comentan que la estimación
⭆ En el **artículo** los creadores comentan que la estimación
(no es necesario el anglicismo)

Además, en el **paper** se describen dos formas de ejecutar la estimación
⭆ Además, en el **artículo** se describen dos formas de ejecutar la estimación
(no es necesario el anglicismo)

estas implementaciones se **puede** utilizar para distintos tipos de ejercicios y de enfermedades
⭆ estas implementaciones se **pueden** utilizar para distintos tipos de ejercicios y de enfermedades
(las «implementaciones» es un plural)

El conjunto de tareas que se han realizado en este sprint **son** 
⭆ El conjunto de tareas que se han realizado en este sprint **han sido** 

Estas tareas por la cantidad de datos y pruebas que se realizaron no se **pudo** terminar en este sprint.
⭆ Estas tareas por la cantidad de datos y pruebas que se realizaron no se **pudieron** terminar en este sprint.
(las «tareas» es plural)

**Lineas** Vodafone (x4)
⭆ **Líneas** Vodafone (x4)

dependiendo de la **vewrsión** CUDA y PyTorch instalada. Por ejemplo, para la **versíón** 10.2 de CUDA
⭆ dependiendo de la **versión** CUDA y PyTorch instalada. Por ejemplo, para la **versión** 10.2 de CUDA

Salarios para empleos de **a.c.s.** informáticos en **españa**.
⭆ Salarios para empleos de **A.C.S.** informáticos en **España**.
(para poder conservar las mayúsculas en las referencias se pone la palabra entre llaves {A.C.S.} o {España})o

A Guide to Convolutional Neural **Netwroks** for Computer Vision
⭆ A Guide to Convolutional Neural **Networks** for Computer Vision

**Comment by Josemi** [comment]
Muchas gracias por las correcciones, hago un push con la nueva versión :).

**Comment by cgosorio** [comment]
Bueno, dado que son errores que he visto durante la lectura, lo correcto me ha parecido informarlos
